
name: Docker Image CI

on:
  push:
    branches: [ "docker-solution" ]
  pull_request:
    branches: [ "docker-solution" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag operating-systems-2/ci-cd-demo:latest
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ghcr.io/operating-systems-2/ci-cd-demo
          labels: latest
  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Fast Webhook
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: http://www.2.cnw2.uclllabs.be:9000/api/webhooks/74668fdc-966a-45f2-869b-66cbdcfe4b92
